<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><TargetFramework>net8.0</TargetFramework><OutputType>Exe</OutputType><ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable></PropertyGroup><ItemGroup><Compile Include="../Shared/InventoryDoorAccess.cs" Link="Shared/InventoryDoorAccess.cs"/><Compile Include="../EventHandler.cs" Link="ExiledHandler.cs"/><Compile Include="../LabAPI/DoorInteractionHandler.cs" Link="LabApiHandler.cs"/></ItemGroup></Project>